### ISSUE TITLE
Extend YAML functionality to include custom SQL in tasks

### ISSUE THREAD

**Issue by redspart** [hung135/dbdifftest#23]
Example:
```YAML
tasks: 
-  DumpTableToExcel:
   oracle-dev:
        sql: select * from TABLE
   sys-dev:
        sql: select * from table
-  GetViewSchemaReference:
-  GetProceSchemaReference:
```
